### PR TITLE
Add custom scrollbar

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Hey @Starboy-Sharma 
Submitting this PR for issue #3 
Screenshot_20230223_105326

### CODE REVIEW

**Comment by Starboy-Sharma** [comment]
thanks @ujwalkumar1995 for you contribution

**Comment by Starboy-Sharma** [comment]
Hey @ujwalkumar1995 
Nice work

I've noticed this scrollbar is not working for firefox. Please fix this for other browsers (Safari, Brave, Firefox) as well.

**Comment by ujwalkumar1995** [comment]
Hey @Starboy-Sharma 
As far as I know, this works in safari and latest version of edge.
Will check for other browsers and raise a separate PR if I can find a good fix.

**Comment by Starboy-Sharma** [comment]
I believe you have to add webkit properties to make it work.

Current view for firefox

image

**Pull request merged**
